#!/bin/sh
. "$(dirname $0)"/common
. "$ETC_PATH"/config


########################################################################################################################
# COMMON FUNCTIONS
########################################################################################################################
quote_sh() {
	sed -e 's|\\|\\\\|g' -e 's|\"|\\\"|g' -e 's|`|\\`|g' -e 's|\\$|\\$|g'
}

display_help() {
    echo "Usage: $0 /path/to/file.tar.gz [option...]" >&2
    echo
    echo "   --maria-db-root-password   MariaDB root password. *required'"
    echo "   --restore-file             Gitlab backup file to restore. *required'"
    echo
    # echo some stuff here for the -a or --add-options
    exit 1
}

########################################################################################################################
# DEFAULTS
########################################################################################################################
current_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

BACKUP_DIR="$SHARE_PATH"/backup
GITLAB_DIR="$SHARE_PATH"/gitlab
GITLAB_PACKAGE_CONTROL="$current_dir"/start-stop-status
MYSQL10_BIN_DIR="$(dirname -- "$MYSQL10_BIN")"

RESTORE_TMP=/tmp/"$GITLAB_NAME"_restore

maria_db_root_password=
restore_file=

########################################################################################################################
# PARAMETER HANDLING
########################################################################################################################
while [ $# -ge 1 ]; do
    case "$1" in
        --maria-db-root-password)
            maria_db_root_password="$2"; shift 2
            if ! [ -z "$maria_db_root_password" ]; then
                MARIADB_PASS="${maria_db_root_password:+-p$maria_db_root_password}"
                if [ "$($MYSQL10_BIN_DIR/mysqladmin ping "$MARIADB_PASS")" != "mysqld is alive" ]; then
                    exit 1
                fi
            fi
        ;;
        --restore-file)
            restore_file="$2"; shift 2
            if ! [ -f $restore_file ]; then
                restore_file="$BACKUP_DIR"/"$restore_file"
                if ! [ -f $restore_file ]; then
                  echo "File: $restore_file not found" >&2
                  exit 1
                fi
            fi
        ;;
        -h | --help)
            display_help  # Call your function
            exit 0
        ;;
        --) # End of all options
            shift
            break
        ;;
        -*)
            echo "Error: Unknown option: $1" >&2
            ## or call function display_help
            exit 1
        ;;
        *)  # No more options
            break
        ;;
    esac
done

########################################################################################################################
# VALIDATE PARAMETER DEPENDENCIES
########################################################################################################################
if [ -z "$maria_db_root_password" ]; then
    echo "--maria-db-root-password is not set!"
    exit 1
fi

if [ -z "$restore_file" ]; then
    echo "--restore-file is not set!"
    exit 1
fi

########################################################################################################################
# UNZIP FILE
########################################################################################################################
if [ -d "$RESTORE_TMP" ]; then
    rm -rf "$RESTORE_TMP"
fi
mkdir -p "$RESTORE_TMP"

echo "extracting $restore_file"
tar xfz "$restore_file" -C "$RESTORE_TMP"

########################################################################################################################
# STOP SYNOLOGY PACKAGE
########################################################################################################################
echo "stopping GitLab"
x=$($GITLAB_PACKAGE_CONTROL stop 2> /dev/null)

########################################################################################################################
# RESTORE DATABASE
########################################################################################################################
echo "restore database"
$MYSQL10_BIN_DIR/mysql -uroot -p$maria_db_root_password -e "DROP DATABASE IF EXISTS $DB_NAME"
$MYSQL10_BIN_DIR/mysql -uroot -p$maria_db_root_password < $RESTORE_TMP"/database.sql"

########################################################################################################################
# RESTORE GITLAB DIR
########################################################################################################################
echo "extracting $RESTORE_TMP/gitlab.tar.gz to $GITLAB_DIR"
rm -rf $GITLAB_DIR
mkdir -p $GITLAB_DIR
tar xpfz $RESTORE_TMP"/gitlab.tar.gz" --strip-components=1 -C $GITLAB_DIR

########################################################################################################################
# FINISH
########################################################################################################################
echo "start GitLab"
x=$($GITLAB_PACKAGE_CONTROL start 2> /dev/null)
rm -rf "$RESTORE_TMP"

echo "restore completed!"
