#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/lib

PKG_NAME=Docker-GitLab
PKG_SHORT=gitlab
ETC_PATH="/var/packages/$PKG_NAME/etc"
TARGET_PATH="/var/packages/$PKG_NAME/target"
SHARE_PATH="$(synoshare --get docker | grep $'\t Path' | sed 's/.*\[\(.*\)].*/\1/')"

if [ "$SYNOPKG_TEMP_LOGFILE" ]; then
	log() {
		local text="$1"
		local idx=0
		shift 1
		for val in "$@"; do
			text="${text/\{$idx\}/$val}"
			let idx=1+$idx
		done
		echo "$text" >> $SYNOPKG_TEMP_LOGFILE
	}
fi
