#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/common
. "$ETC_PATH"/config

[ "$pkgwizard_admin_email" ]                && ADMIN_EMAIL="$pkgwizard_admin_email"
[ "$pkgwizard_hostname" ]                   && HOSTNAME="$pkgwizard_hostname"
[ "$pkgwizard_http_port" ]                  && HTTP_PORT="$pkgwizard_http_port"
[ "$pkgwizard_ssh_port" ]                   && SSH_PORT="$pkgwizard_ssh_port"
[ "$pkgwizard_db_name" ]                    && DB_NAME="$pkgwizard_db_name"
[ "$pkgwizard_db_user" ]                    && DB_USER="$pkgwizard_db_user"
[ "$pkgwizard_db_password" != ___EMPTY___ ] && DB_PASS="$pkgwizard_db_password"

if [ "$pkgwizard_smtp_unchanged" != true ]; then
  [ "$pkgwizard_smtp_enable" ]  && SMTP_ENABLE ="$pkgwizard_smtp_enable"
  [ "$pkgwizard_smtp_address" ] && SMTP_ADDR   ="$pkgwizard_smtp_address"
  [ "$pkgwizard_smtp_port" ]    && SMTP_PORT   ="$pkgwizard_smtp_port"
  [ "$pkgwizard_smtp_user" ]    && SMTP_USER   ="$pkgwizard_smtp_user"
  [ "$pkgwizard_smtp_pass" ]    && SMTP_PASS   ="$pkgwizard_smtp_pass"
  [ "$pkgwizard_smtp_verify"]   && SMTP_VERIFY ="$pkgwizard_smtp_verify"
fi

# fallback for Upgrade from Gitlab 7.x.x
if [ -z "$CI_PARAPHRASE" ]; then
	CI_PARAPHRASE="$(openssl rand -base64 48 | sed 's,/,_,g')"
fi

(
	echo HTTP_PORT="\"$HTTP_PORT\""
	echo SSH_PORT="\"$SSH_PORT\""
	echo UNICORN_TIMEOUT="\"$UNICORN_TIMEOUT\""
	echo DB_NAME="\"$DB_NAME\""
	echo DB_USER="\"$DB_USER\""
	echo DB_PASS="\"$DB_PASS\""
	echo CI_PARAPHRASE="\"$CI_PARAPHRASE\""
	echo HOSTNAME="\"$HOSTNAME\""
	echo ADMIN_EMAIL="\"$ADMIN_EMAIL\""
	echo SMTP_ENABLE="\"$SMTP_ENABLE\""
	echo SMTP_ADDR="\"$SMTP_ADDR\""
	echo SMTP_PORT="\"$SMTP_PORT\""
	echo SMTP_USER="\"$SMTP_USER\""
	echo SMTP_PASS="\"$SMTP_PASS\""
	echo SMTP_VERIFY="\"$SMTP_VERIFY\""
	echo SHARE="\"$SHARE\""
) > "$ETC_PATH"/config

sed -i \
	-e "s/__HTTP_PORT__/$HTTP_PORT/g" \
	"$TARGET_PATH"/ui/config 
	
sed -i \
	-e "s/__REDIS_VERSION__/$REDIS_VERSION/g" \
	"$REDIS_PROFILE"
	
sed -i \
	-e "s/__HTTP_PORT__/$HTTP_PORT/g" \
	-e "s/__SSH_PORT__/$SSH_PORT/g" \
	-e "s/__UNICORN_TIMEOUT__/$UNICORN_TIMEOUT/g" \
	-e "s/__DB_HOST__/$DB_HOST/g" \
	-e "s/__DB_NAME__/$DB_NAME/g" \
	-e "s/__DB_USER__/$DB_USER/g" \
	-e "s/__DB_PASS__/$DB_PASS/g" \
	-e "s/__CI_PARAPHRASE__/$CI_PARAPHRASE/g" \
	-e "s/__HOSTNAME__/$HOSTNAME/g" \
	-e "s/__ADMIN_EMAIL__/$ADMIN_EMAIL/g" \
	-e "s/__SMTP_ENABLE__/$SMTP_ENABLE/g" \
	-e "s/__SMTP_ADDR__/$SMTP_ADDR/g" \
	-e "s/__SMTP_PORT__/$SMTP_PORT/g" \
	-e "s/__SMTP_USER__/$SMTP_USER/g" \
	-e "s/__SMTP_PASS__/$SMTP_PASS/g" \
	-e "s/__SMTP_VERIFY__/$([ "$SMTP_VERIFY" = true ] && echo peer || echo none)/g" \
	-e "s/__GITLAB_VERSION__/$GITLAB_VERSION/g" \
	-e "s/__SHARE__/$SHARE/g" \
	"$GITLAB_PROFILE"

docker pull quay.io/sameersbn/redis:$REDIS_VERSION		
docker pull quay.io/sameersbn/gitlab:$GITLAB_VERSION
	
$API --exec api=SYNO.Docker.Container version=1 method=create is_run_instantly=false profile="$(cat "$REDIS_PROFILE")"
$API --exec api=SYNO.Docker.Container version=1 method=create is_run_instantly=false profile="$(cat "$GITLAB_PROFILE")"

exit 0
