#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

[ "$SYNOPKG_PKG_STATUS" = UPGRADE ] && exit 0

. "$(dirname $0)"/common

if [ -z "$pkgwizard_dataroot" ]; then
	log "$failed_illegal_dir_name" "$pkgwizard_dataroot"
	exit 1
fi

# check mariadb password
if [ ! -z "$pkgwizard_mysql_password" ]; then
	if [ "$(mysqladmin ping -p"$pkgwizard_mysql_password")" != "mysqld is alive" ]; then
		log "$failed_db_connect"
		exit 1
	fi
elif [ ! mysql -u$pkgwizard_db_user -p"$pkgwizard_db_password" $pkgwizard_db_name -e exit ]; then
	log "$failed_db_connect"
	exit 1
fi

# check share create
dataPath="$SHARE_PATH/$pkgwizard_dataroot"
if ! mkdir -p "$dataPath"; then
	log "$failed_illegal_dir_name" "$pkgwizard_dataroot"
	exit 1
fi
chmod 755 "$dataPath"

exit 0
