#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/common
. "$ETC_PATH"/config

[ "$pkgwizard_db_name" ]      && DB_NAME="$pkgwizard_db_name"
[ "$pkgwizard_db_user" ]      && DB_USER="$pkgwizard_db_user"
[ "$pkgwizard_db_password" ]  && DB_PASS="$pkgwizard_db_password"

# check database
if [ ! mysql -u$DB_USER -p"$DB_PASS" $DB_NAME -e exit ]; then
	log "$failed_db_connect"
	exit 1
fi

/usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container version=1 method=delete name=synology_gitlab_redis force=true preserve_profile=false
/usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container version=1 method=delete name=synology_gitlab force=true preserve_profile=false

docker rmi quay.io/sameersbn/redis:$REDIS_VERSION
docker rmi quay.io/sameersbn/gitlab:$GITLAB_VERSION

exit 0
