#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/common
UI_PATH="/usr/syno/synoman/webman/3rdparty/$PKG_NAME"
DOCKER_BIN=/usr/local/bin/docker
WEBAPI_BIN=/usr/syno/bin/synowebapi

case "$1" in
	start)
		[ -d "$TARGET_PATH"/ui ] && ln -s "$TARGET_PATH"/ui "$UI_PATH"
		# start gitlab twice to prevent /etc/host missing error
		"$WEBAPI_BIN" --exec api=SYNO.Docker.Container version=1 method=start name="$GITLAB_NAME" && exit 0
		"$WEBAPI_BIN" --exec api=SYNO.Docker.Container version=1 method=start name="$GITLAB_NAME" && exit 0
		exit 1
		;;

	stop)
		rm "$UI_PATH"
		"$WEBAPI_BIN" --exec api=SYNO.Docker.Container version=1 method=stop name="$GITLAB_NAME" || exit 1
		"$WEBAPI_BIN" --exec api=SYNO.Docker.Container version=1 method=stop name="$REDIS_NAME"  || exit 1
		exit 0
		;;

	status)
		"$DOCKER_BIN" inspect "$GITLAB_NAME" | grep -q "\"SynoStatus\": \"running\"," || exit 1
		"$DOCKER_BIN" inspect "$REDIS_NAME"  | grep -q "\"SynoStatus\": \"running\"," || exit 1
		exit 0
		;;

	*)
		exit 1
		;;
esac
