#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/lib

PKG_NAME=Docker-GitLab
PKG_SHORT=gitlab
ETC_PATH="/var/packages/$PKG_NAME/etc"
TARGET_PATH="/var/packages/$PKG_NAME/target"
SHARE_PATH="$(synoshare --get docker | grep $'\t Path' | sed 's/.*\[\(.*\)].*/\1/')"

DB_HOST=$(ip address show docker0 | grep inet | awk '{print $2}' | cut -f1 -d/ | head -n 1)
API=/usr/syno/bin/synowebapi

# Gitlab Version can be taken from here 
# https://quay.io/repository/sameersbn/gitlab?tab=tags
GITLAB_VERSION=8.16.3
GITLAB_NAME=synology_gitlab
GITLAB_PROFILE="$TARGET_PATH"/config/"$GITLAB_NAME"

# Redis Version can be taken fom here
# https://quay.io/repository/sameersbn/redis?tab=tags
REDIS_VERSION=latest
REDIS_NAME=synology_gitlab_redis
REDIS_PROFILE="$TARGET_PATH"/config/"$REDIS_NAME"

UNICORN_TIMEOUT=180
GITLAB_SECRETS_OTP_KEY_BASE=/volume1/docker/gitlab/.secret

if [ "$SYNOPKG_TEMP_LOGFILE" ]; then
	log() {
		local text="$1"
		local idx=0
		shift 1
		for val in "$@"; do
			text="${text/\{$idx\}/$val}"
			let idx=1+$idx
		done
		echo "$text" >> $SYNOPKG_TEMP_LOGFILE
	}
fi
