#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

[ "$SYNOPKG_PKG_STATUS" = UPGRADE ] && exit 0

. "$(dirname $0)"/common

# check mariadb password
if [ "$pkgwizard_delete_data" = true ]; then
	if [ "$(mysqladmin ping -p"$pkgwizard_mysql_password")" != "mysqld is alive" ]; then
		log "$failed_db_connect"
		exit 1
	fi
fi 

exit 0
